Traceback (most recent call last):
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# dictionary of climatology functions results
ncl_results = {
    "calcDayAnomTLL": -0.02774364,
    "calcMonAnomTLL": 0.003319263,
    "clmDayTLL": 0.7408184,
    "clmMonTLL": 0.8063018,
    "month_to_season": 0.9931215,
    "rmMonAnnCycTLL": 0.003319263,
    "stdMonTLL": 0.07392025,
}

for c in ncl_results.keys() & results.keys():
    print(f"{c}: \n\tpython:\t\t{results[c]}\n\tncl:\t\t{ncl_results[c]}\n")
    assert math.isclose(
        ncl_results[c], results[c], rel_tol=1e-06
    )  # within 6 decimal points
------------------

----- stdout -----
month_to_season: 
	python:		0.9931214451789856
	ncl:		0.9931215

clmDayTLL: 
	python:		0.7408185005187988
	ncl:		0.7408184

calcMonAnomTLL: 
	python:		0.0033192038536071777
	ncl:		0.003319263
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 14[0m
[1;32m     12[0m [38;5;28;01mfor[39;00m c [38;5;129;01min[39;00m ncl_results[38;5;241m.[39mkeys() [38;5;241m&[39m results[38;5;241m.[39mkeys():
[1;32m     13[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mc[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124mpython:[39m[38;5;130;01m\t[39;00m[38;5;130;01m\t[39;00m[38;5;132;01m{[39;00mresults[c][38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124mncl:[39m[38;5;130;01m\t[39;00m[38;5;130;01m\t[39;00m[38;5;132;01m{[39;00mncl_results[c][38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[0;32m---> 14[0m     [38;5;28;01massert[39;00m math[38;5;241m.[39misclose(
[1;32m     15[0m         ncl_results[c], results[c], rel_tol[38;5;241m=[39m[38;5;241m1e-06[39m
[1;32m     16[0m     )  [38;5;66;03m# within 6 decimal points[39;00m

[0;31mAssertionError[0m: 

